baseURL = 'https://vosca.dev/'
languageCode = 'en-us'
title = 'V Open Source Community Association'
ignoreFiles = [".scss$", ".ts$"]

[params]
visibleTitle = 'Association'

[minify]
minifyOutput = true
